apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eemcars-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - target:
      kind: Deployment
      name: eemcars-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: eemcars-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: eemcars-celery-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: eemcars-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

configMapGenerator:
  - name: eemcars-config
    behavior: merge
    literals:
      - log-level=DEBUG
      - api-url=https://api-dev.eemcars.io/api/v1
